receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317
      http: 
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  file:
    path: /data/exports.json    
  debug:
    verbosity: detailed
  prometheus:
    endpoint: ":9201"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
  otlphttp/logs:
      endpoint: "http://host.docker.internal:4318/api/OtlpToDcr"
      tls:
        insecure: true
      encoding: json
                  

processors:
  transform/observedtime:
    log_statements:
      - context: log
        statements:
          - set(log.observed_time_unix_nano, UnixNano(Time(log.attributes["ts"],"%Y-%m-%dT%H:%M:%S.%f")))
          - set(log.time_unix_nano, UnixNano(Time(log.attributes["ts"],"%Y-%m-%dT%H:%M:%S.%f")))
        conditions:
         - IsString(attributes["ts"])
  attributes/empty:
    actions:
      - key: "empty"
        # match empty string
        pattern: ^\s*$
        action: delete        

service:
  telemetry:
      logs:
        level: debug
      traces:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp,debug,azuremonitor]
    logs:
      receivers: [otlp]
      processors: [attributes/empty]
      exporters: [otlphttp/logs,debug]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]

